### ISSUE TITLE
Update rules with our conventions

### ISSUE THREAD

**Issue by jrubins** [neighborhoods/Facade-Inspector#1]
## Our Custom Linting Rules
- displayName must always be included
- doc Block for esdoc must be correct format
- fetch and defer on components must be static and include dispatch
- Static method/props, prop, constructor, LifeCycle methods, everything else, render last
- Always bind in constructor
## Our Available Linting Rules
- 1 component per file
-  no _ prefixes
- no extension
- 140 max line lne
- global require only
- underscore dangle
- react/jsx-boolean-value (remove)
- require quotes around object literal property names
- Restrict file extensions that may be required (tweak webpack)
- only .jsx files may have JSX

**Comment by zrosenbauer** [comment]
@jrubins just a note the custom rules might actually available I just did not check, in addition confirm with the JS style guide that this includes all conventions

**Comment by zrosenbauer** [comment]
Have we made any progress on this?
