### ISSUE TITLE
import-order plugin

### ISSUE THREAD

**Issue by zrosenbauer** [neighborhoods/Facade-Inspector#12]
It seems having current implementation is still missing the plugin somehow

**Comment by jrubins** [comment]
I don't think I understand that sentence...

**Comment by zrosenbauer** [comment]
lol wrote that quickly, I'll fix it this week, the import-order plugin was throwing a strange error when running it locally.

**Comment by zrosenbauer** [comment]
moved to jira as tech-debt, will reopen if this is issue with-in the config package
