### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by zrosenbauer** [neighborhoods/Facade-Inspector#9]
Should be more aptly named

Suggestions:
- `Neighborhoods-Facade-Code-Styles`
- `Facade-Code-Styles`
- `Neighborhoods-Facade-Code-Styleguide`

etc.

**Comment by jrubins** [comment]
I think I like `Neighborhoods-Facade-Code-Styles` the most.

**Comment by zrosenbauer** [comment]
@55places/facade thoughts?

**Comment by zrosenbauer** [comment]
@cbourdage my vote is `Neighborhoods-Facade-Code-Styles` also.
